language: python
python:
    - 2.7
env:
    - PLONE_VERSION=4.2
install:
    - sed -ie "s#test-4.2.x.cfg#test-$PLONE_VERSION.x.cfg#" travis.cfg
    - python bootstrap.py
    - bin/buildout -c travis.cfg
script:
    - bin/test
after_success:
    - bin/coverage
    - bin/coveralls
